config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, except: :index do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list # list en haut et .list sont le même
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
   @bookmark = Bookmark.find(params[:id])
   @bookmark.destroy
   redirect_to list_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id) # because of through dans le model
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>bookmark, yes! </h1>

<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="m-4 d-flex align-items-center justify-content-between">
  <h1>Mooooooovies! list</h1>
  <%= link_to "Add a list", new_list_path, class: "btn btn-dark"%>
</div>
<ul>
  <% @lists.each do |list| %>
    <li class="list-inline">
      <%= list.name %>
      <%=link_to list.name, list_path(list) %>
    <% end %>
  </li>
</ul>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form", list: @list %>
<%= link_to "Back to the Movie list", root_path %>

app/views/lists/show.html.erb
<div class="m-3">
  <h2><%= @list.name %></h2>
  <div>
    <% @list.bookmarks.each do |bookmark| %>
      <%= bookmark.movie.title %>
      <%= bookmark.movie.overview %>
      <br>
      <%= bookmark.comment %>
      <%= link_to "Delete", bookmark_path(bookmark), #action de mon controller bookmarks, pas lists
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <br>
      <% end %>
  </div>
  <div>
    <%= link_to "New Bookmark", new_list_bookmark_path(@list), class: "btn btn-dark"%>
    <%= link_to "Back to the Movie list", root_path %>
  </div>
</div>